### ISSUE TITLE
Error: Response closed without grpc-status (Headers only)

### ISSUE THREAD

**Issue by thaibossaw** [grpc/grpc-web#1046]
I have the following message and service definitions

```
/**
* User model
*/
message User {
  string user_id = 1; // MongoDB unique identifier
  string email = 2; // User's email address
  string password = 3;
  Role role = 4;
  int64 created = 5; // Creation timestamp
  string creator = 6; // Email address of the creator
  bool disabled = 7; // Manual lockout flag
  int32 auth_failures = 8; // Auth failure count
  bool locked = 9; // Auto lockout flag
  string token = 10; // JWT token for post login auth
  string name = 11;
  int64 updated = 12;
}
```

```
service Users {
  // Login and get JWT token
  rpc login(Login) returns (User) {}
.....
```

And the following service method on my Python server:

```
def login(self, request, context):
        if not request.email:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details('The username/password provided is incorrect')
            return messages_pb2.LoginResponse(error='The username/password provided is incorrect')

        user = self.db.users.find_one({'email': request.email})
        return messages_pb2.User(**user)
```

When calling from another client, such as one written in Python, the request is absolutely fine. 

However, when calling from grpc-web with the ImprobableEngGrpcWebClient in angular, I get the following error:

```
users.service.ts:70 Error: Response closed without grpc-status (Headers only)
    at Object.onEnd (messages_pb_service.js:69) [angular]
    at :4200/vendor.js:86815:24343 [angular]
    at :4200/vendor.js:86815:4892 [angular]
    at Array.forEach (<anonymous>) [angular]
    at e.rawOnEnd (grpc-web-client.umd.js:1) [angular]
    at e.onTransportEnd (grpc-web-client.umd.js:1) [angular]
    at :4200/vendor.js:86815:13311 [angular]
    at Object.onInvoke (core.js:28301) [angular]
    at :4200/polyfills.js:1165:40 [angular]
    at Object.onInvokeTask (core.js:28289) [angular]
```

It's definitely not a connection issue, as I get a HTTP 200 response, and the body of the request contains the data that's expected:

```
Request URL: http://localhost:8080/Protos.Users/login
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer-when-downgrade
accept-encoding: identity,gzip
access-control-allow-origin: http://localhost:4200
access-control-expose-headers: custom-header-1,grpc-status,grpc-message
content-type: application/grpc-web+proto
date: Sat, 20 Feb 2021 12:45:10 GMT
grpc-accept-encoding: identity,deflate,gzip
server: envoy
transfer-encoding: chunked
x-envoy-upstream-service-time: 3

```
And the response body:

```

603006a4236cfd11f7bd0d5dsystem.admin@testing.com<$2b$10$.kLFgFLqz/2z8idQJweZZuLsr8e6T06WL5QuiUBf.ef3j0t1HLtI6 (óÀZSystem Admin`óÀgrpc-status:0
grpc-message:

```

And the envoy debug log:

```
[2021-02-20 12:57:17.326][69423][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:190] [C1] using existing connection
[2021-02-20 12:57:17.326][69423][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:130] [C1] creating stream
[2021-02-20 12:57:17.326][69423][debug][router] [external/envoy/source/common/router/upstream_request.cc:354] [C0][S17761285570082037057] pool ready
[2021-02-20 12:57:17.326][69423][debug][http] [external/envoy/source/common/http/filter_manager.cc:755] [C0][S17761285570082037057] request end stream
[2021-02-20 12:57:17.330][69423][debug][router] [external/envoy/source/common/router/router.cc:1174] [C0][S17761285570082037057] upstream headers complete: end_stream=false
[2021-02-20 12:57:17.330][69423][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1484] [C0][S17761285570082037057] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'application/grpc-web+proto'
'grpc-accept-encoding', 'identity,deflate,gzip'
'accept-encoding', 'identity,gzip'
'x-envoy-upstream-service-time', '4'
'access-control-allow-origin', 'http://localhost:4200'
'access-control-expose-headers', 'custom-header-1,grpc-status,grpc-message'
'date', 'Sat, 20 Feb 2021 12:57:17 GMT'
'server', 'envoy'

[2021-02-20 12:57:17.330][69423][debug][client] [external/envoy/source/common/http/codec_client.cc:112] [C1] response complete
[2021-02-20 12:57:17.330][69423][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:159] [C1] destroying stream: 0 remaining
[2021-02-20 12:57:17.331][69423][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1500] [C0][S17761285570082037057] encoding trailers via codec:
```

Anyone got any ideas what's causing this?

**Comment by thaibossaw** [comment]
Nevermind. turns out there was a discrepancy between two proto files and it was throwing the client for a loop.
