### ISSUE TITLE
Error when deserializing response data; error: Error: Assertion failed in 1.5.0

### ISSUE THREAD

**Issue by eqinox76** [grpc/grpc-web#1460]
Hey all,

i think i found a regression bug from 1.4.2 to 1.5.0. A response message cannot be parsed and causes the mentioned error.
The message is as follows:
```
echo 'AAAAAHAI+sEKEgcIDRIDVVNEGAgiHENhbGwgVVNETVhOIDIwMjQtMDctMjQgMTguOTkqBCtNWE46DQjv54IBEgQrTVhOGAE6DQjw54IBEgQrTVhOGBJyHQitUxANIAEoAjoHCOgPEAcYGEGTGARWDv0yQEgBgAAAABBncnBjLXN0YXR1czogMA0K' | base64 -d | hexdump -C
00000000  00 00 00 00 70 08 fa c1  0a 12 07 08 0d 12 03 55  |....p..........U|
00000010  53 44 18 08 22 1c 43 61  6c 6c 20 55 53 44 4d 58  |SD..".Call USDMX|
00000020  4e 20 32 30 32 34 2d 30  37 2d 32 34 20 31 38 2e  |N 2024-07-24 18.|
00000030  39 39 2a 04 2b 4d 58 4e  3a 0d 08 ef e7 82 01 12  |99*.+MXN:.......|
00000040  04 2b 4d 58 4e 18 01 3a  0d 08 f0 e7 82 01 12 04  |.+MXN..:........|
00000050  2b 4d 58 4e 18 12 72 1d  08 ad 53 10 0d 20 01 28  |+MXN..r...S.. .(|
00000060  02 3a 07 08 e8 0f 10 07  18 18 41 93 18 04 56 0e  |.:........A...V.|
00000070  fd 32 40 48 01 80 00 00  00 10 67 72 70 63 2d 73  |.2@H......grpc-s|
00000080  74 61 74 75 73 3a 20 30  0d 0a                    |tatus: 0..|
```

I cannot see anything special about it. But v1.5.0 cannot parse it while v1.4.2, the golang grpc client, [grpc-ui](https://github.com/fullstorydev/grpcui) or [grpcurl](https://github.com/fullstorydev/grpcurl) are working as expected.

Regards,
Carsten

**Comment by Emulator000** [comment]
experiencing the same issue, this this minimal code:
```ts
try {
  const testSerialization = User.deserializeBinary(
    new Uint8Array(Array.from(user.serializeBinary())),
  );
  console.log(testSerialization);
} catch (err) {
  console.log(err);
}
```

I get this exception:
```
Error: Assertion failed
    at sa (google-protobuf.js:13:214)
    at n (google-protobuf.js:13:311)
    at J.ra (google-protobuf.js:72:312)
    at proto.tfs.core.api.public.authenticated.UserSettings.deserializeBinaryFromReader (api.public.authenticated_pb.js:13936:96)
    at J.Yb (google-protobuf.js:67:146)
    at proto.tfs.core.api.public.authenticated.User.deserializeBinaryFromReader (api.public.authenticated_pb.js:13120:14)
    at proto.tfs.core.api.public.authenticated.User.deserializeBinary (api.public.authenticated_pb.js:13076:55)
    at eval (me-context-provider.tsx:172:50)
```

debugging the code the problem is inside one of the generated `readEnum()` functions, when it goes here:
```
J.prototype.ra = function() {
    n(0 == this.b);
    return this.a.sa()
}
;
J.prototype.readEnum = J.prototype.ra;
```

I noted that `this.b` is 3 instead of 0 for some reason.

**Comment by sampajano** [comment]
@eqinox76 Thanks for the report!

Do you mind sharing the exact error what you encountered in 1.5.0?

Protobuf parsing is done in the generated JSPB files (which contains `jspb.Message`), i.e. by https://github.com/protocolbuffers/protobuf-javascript, so it is somewhat surprising that it's regressing in the new grpc-web release.

**Comment by eqinox76** [comment]
Hey @sampajano,

i am sorry for the confusion. I cannot reproduce it with 1.5.0 and cannot find the full error message in my history. 
Its very likely my fault.

Regards,
Carsten

**Comment by sampajano** [comment]
@eqinox76 Hi! Thanks for the update!! No worries at all! Glad it worked out for you! 😊
