### ISSUE TITLE
client side http2 support?

### ISSUE THREAD

**Issue by xzzh999** [grpc/grpc-web#432]
Hi~  great work!

Now i want to use ```grpc-web``` as the client side and [```grpc-java```](https://github.com/grpc/grpc-java) as the server side to make the rpc call, 
but after request code called, there were some error:

**proto**
```
syntax = "proto3";

option java_package = "com.xxx.xxxxxx.proto_out";


// The stream service definition.
service PlayStream {
    // Sends a greeting
    rpc PlayStreamGetInfo (StreamReq) returns (StreamAck) {}
}

// The request message containing the user's name.
message StreamReq {
    uint32 camera_id = 1;
}

// The response message containing the greetings
message StreamAck {
    uint32 camera_id = 1;
    string play_url = 2;
}
```

**request** (http)
```
let test_obj = new PlayStreamClient('http://localhost:9898', null, null);
            let request = new StreamReq();
            request.setCameraId(1);
            test_obj.playStreamGetInfo(request, {}, function(err, response){
                console.log(response);
            });
```
**error**
```
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: OPTIONS /PlayStream/PlayStreamGetInfo 
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)

```
and then i **change the request** to **https**:
```
let test_obj = new PlayStreamClient('https://localhost:9898', null, null);
```
the **errors:**
```
2019-01-10 17:32:20.562 INFO  io.grpc.netty.NettyServerTransport.connections - Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 1603010200010001fc030328c6f84d3168505fcbc5ab169f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:318)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
```

How should i to solve this ?  and **i don't want any proxy (envoy or nginx)**,  just make directly call...
Need u help, thx.

**Comment by stanley-cheung** [comment]
Direct http/2 connection to gRPC backend is currently not supported.

**Comment by frankbenoit** [comment]
@stanley-cheung is there a chance this problem (direct http/2) gets solved in near time?

**Comment by ikhoon** [comment]
> Now i want to use grpc-web as the client side and grpc-java as the server side to make the rpc call

@xzzh999 [Armeria](https://armeria.dev/docs#integration-with-grpc-and-thrift) gRPC server can serve gRPC-over-HTTP/1.1

**Comment by alexanderkyte** [comment]
Can you document a workaround?
