### ISSUE TITLE
Helloworld example fail to build on production mode

### ISSUE THREAD

**Issue by pasdam** [grpc/grpc-web#451]
The [helloworld example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld) fail to compile in production mode, when running the command:

```sh
npx webpack client.js
```

I get the following error:

```
ERROR in main.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (~/workspace/github/grpc/grpc-web/net/grpc/gateway/examples/helloworld/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (~/workspace/github/grpc/grpc-web/net/grpc/gateway/examples/helloworld/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (~/workspace/github/grpc/grpc-web/net/grpc/gateway/examples/helloworld/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (~/workspace/github/grpc/grpc-web/net/grpc/gateway/examples/helloworld/node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:197:13)
    at emit (internal/child_process.js:828:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

whereas using:

```
npx webpack client.js --mode development
``` 

succeeds.

---

Edit:

Step to reproduce:
```sh
git clone git@github.com:grpc/grpc-web.git
cd grpc-web/net/grpc/gateway/examples/helloworld/
npm install
npx webpack client.js
```

**Comment by stanley-cheung** [comment]
hm, sorry I don't particular quite follow. Where does `minify` come from? I search the codebase but can't find any.

On the other hand, the default example in our repo do specify `mode: production`. https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/commonjs-example/webpack.config.js with no problem. 

Can you clarify your steps to reproduce please? Thanks.

**Comment by pasdam** [comment]
Sorry I added the step to reproduce, but basically I just followed the steps in the section [Compile the client javascript code](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#compile-the-client-javascript-code) in the README of the example.

Also what I'm saying is that by default it compile for production and that fails.

**Comment by stanley-cheung** [comment]
I am closing some of these older bugs.

For this one: you need to follow the section just above https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#generate-protobuf-messages-and-client-service-stub to generate the classes from the `helloworld.proto` first. Then running `npx webpack client.js --mode production` should work. I just tried it again.
