### ISSUE TITLE
Getting error while run grpc-web in electron... XMLHTTPRequest is not defined

### ISSUE THREAD

**Issue by techgourav** [grpc/grpc-web#453]
Error Logs:

ReferenceError: XMLHttpRequest is not defined
    at goog.net.DefaultXmlHttpFactory.createInstance (webpack:///./node_modules/grpc-web/index.js?:324:126)
    at Object.goog.net.XmlHttp (webpack:///./node_modules/grpc-web/index.js?:322:1501)
    at goog.net.XhrIo.createXhr (webpack:///./node_modules/grpc-web/index.js?:396:250)
    at goog.net.XhrIo.send (webpack:///./node_modules/grpc-web/index.js?:391:345)
    at module$contents$grpc$web$GrpcWebClientBase_GrpcWebClientBase.rpcCall (webpack:///./node_modules/grpc-web/index.js?:470:441)
    at proto.carbine.CommandServiceClient.install (webpack:///./src/main/protocol/carbine_grpc_web_pb.js?:103:23)
    at Module.eval (webpack:///./src/main/main.ts?:61:8)
    at eval (webpack:///./src/main/main.ts?:66:30)
    at Module../src/main/main.ts (/home/gourav.m/go/src/carbine/client/dist/main.bundle.js:119:1)
    at __webpack_require__ (/home/gourav.m/go/src/carbine/client/dist/main.bundle.js:20:30)

**Comment by stanley-cheung** [comment]
gRPC-Web is meant to be run from the browsers only.

**Comment by buckhx** [comment]
Mentioned in another repo, but exposing the transport as the improbable project does would allow for this project to be run on the server. It may seem counter-intuitive, but there is a big trend in server side rendered javascript applications as well as javascript rendered frameworks such as Electron referenced from this parent issue. Happy to elaborate in a separate issue, but is a dealbreaker for us to use this project on a major public application.

**Comment by johanbrandhorst** [comment]
Is just using the official Node gRPC library an option for server-side rendering?

**Comment by Kupstas** [comment]
What is official position about supporting SSR?

**Comment by abonander** [comment]
> gRPC-Web is meant to be run from the browsers only.

This is unhelpful as it's nice to be able to test during prototyping before going through the ordeal of setting up Browserify/Webpack.

**Comment by joeporpeglia** [comment]
I ended up polyfilling `XMLHttpRequest` using the [`xhr2` package](https://www.npmjs.com/package/xhr2) (I also tried `xmlhttprequest` with no luck). So far it seems to be working!

Just added this to the ssr entry point (or any place that will avoid bundling it and sending to the browser):
```js
global.XMLHttpRequest = require('xhr2');
```

**Comment by abonander** [comment]
We ended up switching back to `@improbable-eng/grpc-web` because it supports both Node and browser transparently without any hacks on our end.

**Comment by isc30** [comment]
@joeporpeglia did you find any cases where the `xhr2` package didn't work?

**Comment by joeporpeglia** [comment]
@isc30 fortunately no, but I wasn't doing much beyond simple GET/POST requests

**Comment by sampajano** [comment]
Also see https://github.com/grpc/grpc-web/issues/1134 where a user has found a temporary workaround for using within service workers :)

**Comment by windmaple** [comment]
`xhr2` package didn't work for me either

/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:64
function Oc(a,b,c){var d=!1,f=null,g=!1;a.on("data",function(e){d=!0;f=e});a.on("error",function(e){0==e.code||g||(g=!0,b(e,null))});a.on("status",function(e){0==e.code||g?c&&b(null,null,e):(g=!0,b({code:e.code,message:e.details,metadata:e.metadata},null))});if(c)a.on("metadata",function(e){b(null,null,null,e)});a.on("end",function(){g||(d?b(null,f):b({code:2,message:"Incomplete response"}));c&&b(null,null)})}
                                                                                                                        ^

TypeError: b is not a function
    at Array.<anonymous> (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:64:121)
    at Y (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:56:358)
    at oc.<anonymous> (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:55:61)
    at Ib (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:33:182)
    at O (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:32:614)
    at wc (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:43:411)
    at yc (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:46:228)
    at oc.n.W (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:44:252)
    at oc.n.R (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/grpc-web/index.js:44:231)
    at XMLHttpRequest.dispatchEvent (/Users/windmaple/Desktop/tfserving-web/nodejs/node_modules/xhr2/lib/xhr2.js:76:20)
