### ISSUE TITLE
Bazel build with closure_grpc_web_library fails 

### ISSUE THREAD

**Issue by sholokhov** [grpc/grpc-web#521]
Hi!
I'm trying to use `closure_grpc_web_library` rule in bazel build to generate js lib from my protobufs, but it fails with the following trace:

```
bazel build //myservice-api:myservice_service_grpc_web_proto --incompatible_disallow_filetype=false --incompatible_disallow_data_transition=false
INFO: Invocation ID: 8f79d17a-aecb-4ac2-a350-6ced30761f39
ERROR: /private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl:5:1: file '@io_bazel_rules_closure//closure/compiler:closure_js_library.bzl' does not contain symbol 'create_closure_js_library'
ERROR: /private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl:9:1: file '@io_bazel_rules_closure//closure/private:defs.bzl' does not contain symbol 'CLOSURE_JS_TOOLCHAIN_ATTRS'
ERROR: /private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl:14:1: file '@io_bazel_rules_closure//closure/protobuf:closure_proto_library.bzl' does not contain symbol 'closure_proto_aspect' (did you mean '_closure_proto_aspect'?)
ERROR: /private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl:161:24: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl", line 154
                rule(implementation = _closure_grpc_w..., ...))
        File "/private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl", line 156, in rule
                dict({"deps": attr.label_list(mandato..."))}, ...)
        File "/private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl", line 157, in dict
                attr.label_list(mandatory = True, providers = [Pro..."], ...])
        File "/private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_github_grpc_grpc_web/bazel/closure_grpc_web_library.bzl", line 161, in attr.label_list
                closure_proto_aspect
global variable 'closure_proto_aspect' is referenced before assignment.
ERROR: Skipping '//myservice-api:myservice_service_grpc_web_proto': error loading package 'myservice-api': Extension file 'bazel/closure_grpc_web_library.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'myservice-api': Extension file 'bazel/closure_grpc_web_library.bzl' has errors
INFO: Elapsed time: 0.424s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

WORKSPACE:
```
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "b29a8bc2cb10513c864cb1084d6f38613ef14a143797cea0af0f91cd385f5e8c",
    strip_prefix = "rules_closure-0.8.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.8.0.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/0.8.0.tar.gz",
    ],
)
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()

git_repository(
    name = "com_github_grpc_grpc_web",
    commit = "ffe8e9c9036f4ec7d5b55da75b1758b1f57fbf8d",
    remote = "https://github.com/grpc/grpc-web.git",
)
```

Build rules:
```
proto_library(
    name = "myservice_service_proto",
    srcs = [ "src/main/protobuf/MyService.proto" ],
    deps = [
        "@com_google_protobuf//:empty_proto"
    ]
)

closure_grpc_web_library(
    name = "myservice_service_grpc_web_proto",
    deps = [
        ":myservice_service_proto",
    ],
)
```

Bazel info:
```
 bazel version
Build label: 0.24.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Mar 26 16:15:16 2019 (1553616916)
Build timestamp: 1553616916
Build timestamp as int: 1553616916
```

Seems like something wrong with `closure_proto_aspect` exposing from `io_bazel_rules_closure`, any thoughts or ideas? Or am I doing something completely wrong? :)

**Comment by Yannic** [comment]
IIRC `closure_grpc_web_library` requires changes that are not in `rules_closure@0.8.0`. Can you try to build it with `rules_closure@head`? (This also fixes a couple of `--incompatible_*` errors you might see).

**Comment by sholokhov** [comment]
Thanks for a quick reply @Yannic!

With `rules_closure@head` it starts, but fails with another issues: 

```
ERROR: /private/var/tmp/_bazel_sholokhov/c4bf13ed72c705dc8b3517a4c5026ae8/external/com_google_guava/BUILD:7:1: no such package '@com_google_errorprone_error_prone_annotations//': BUILD file not found on package path and referenced by '@com_google_guava//:com_google_guava'
ERROR: Analysis of target '//myservice-api:myservice_service_grpc_web_proto' failed; build aborted: no such package '@com_google_errorprone_error_prone_annotations//': BUILD file not found on package path
INFO: Elapsed time: 0.474s
```

It seems like I have to [override dependencies](https://github.com/bazelbuild/rules_closure#overriding-dependency-versions) for closure rules, so it shouldn't be related to `grpc-web` anymore. Thanks for help!
