### ISSUE TITLE
Error with docker compose up

### ISSUE THREAD

**Issue by ashwin027** [grpc/grpc-web#953]
Im  trying to follow the instructions for the tutorial in the readme. The docker compose pull works fine but the docker compose up ended with an error,

docker-compose up node-server envoy commonjs-client
Output:
Building prereqs
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1078, in up
  File "compose\cli\main.py", line 1074, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 367, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 261, in build
  File "site-packages\docker\api\build.py", line 308, in _set_auth_headers
  File "site-packages\docker\auth.py", line 311, in get_all_credentials
  File "site-packages\docker\auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages\docker\auth.py", line 287, in _get_store_instance
  File "site-packages\docker\credentials\store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[19576] Failed to execute script docker-compose

After installing the gcloud cli, this error went away. Is the gcloud cli a pre-requisite?

**Comment by stanley-cheung** [comment]
Not that I am aware of. I haven't seen this error before. Those example docker images should have nothing to do with gcloud cli.
